### ISSUE TITLE
Show "latest movies"

### ISSUE THREAD

**Issue by leogallego** [j0hn/guicavane#10]
Once you choose "Movies" in  the dropdown, maybe it would be useful to have the latest movies listed.

**Comment by j0hn** [comment]
This feature has been added in the develop branch... it looks something like this:

![screenshot](http://i.imgur.com/FpgvZ.png)

I have also added a "Recommended movies" mode.
Some test on this and maybe feedback would be great.

Thanks!

**Comment by nikod** [comment]
Estaria bueno agregarlo para las series tambien
