### ISSUE TITLE
Error downloading

### ISSUE THREAD

**Issue by theHazzard** [j0hn/guicavane#16]
Hi there, I'm Enzo from Argentina
I'm having an error while I'm trying to download an episode of weeds, last one last season, I think there is a problem with the characters in the name 'ie: \', I remove the template tag who writes the name of the episode, and that way works fine (writes the file on the disk without errors)
I submit an image with the error given
greetings people, and forgive me for my bad english!
http://imageshack.us/photo/my-images/401/errordw.png/

**Comment by curita** [comment]
Hi Enzo, thanks for reporting this error. I've corrected it, and I let you know when the new exe file fixing this issue is uploaded :)

**Comment by changeme** [comment]
Hi.
I have a similar fail here, with Futurama: Möbius Dick (I think the problem is at [ö] )

My OS: Windows 7

**Comment by godlike64** [comment]
The same thing happens on Linux if the filename has any weird unicode character (e.g. "Cacería De Brujas", note the "'i"). It is not exactly the same problem but it is related. Some characters need to be escaped in some way so as to be saved normally (and anyway "/" will cause trouble in Linux too, regardless the filesystem in use).
