### ISSUE TITLE
no Abre en KDE 

### ISSUE THREAD

**Issue by MikeSoft** [j0hn/guicavane#19]
###### ###### /Linux/guicavane$ guicavane

Traceback (most recent call last):
  File "/usr/local/bin/guicavane", line 12, in <module>
    import gtk
## ImportError: No module named gtk

y finalmente no ejecuta nada

**Comment by j0hn** [comment]
tenes que tener instalada la librería gtk y los bindings para python que no viene por defecto en kde.

**Comment by MikeSoft** [comment]
me pusiste a buscar :S :D
