### ISSUE TITLE
Base de datos offline

### ISSUE THREAD

**Issue by ivanalejandro0** [j0hn/guicavane#21]
Estaria bueno tener la posibilidad de bajar la base de datos de peliculas y series por si la pagina de cuevana esta funcionando mal o esta saturada tener todo a mano y poder ver las series/peliculas igual :)
Seria como un modo 'desconectado' de cuevana.tv
Se me ocurrio al ver este post en neoteo: http://www.neoteo.com/cliente-de-escritorio-para-cuevana
promocionan otro programa con esa caracteristica... de paso les deje un comentario para que prueben guicavane :D

Saludos

**Comment by j0hn** [comment]
Estamos trabajando en ese feature en particular en estos momentos. De hecho ya está funcionando con la base de datos de Freevana. Si queres probarlo fijate de pasarte la branch "sites" que es donde estamos trabajando en eso, aunque todo está muy experimental.

Si no sabes como pasarte al branch sites te dejo las instruciones:

$ git clone https://github.com/j0hn/guicavane.git
$ cd guicavane
$ git fetch
$ git checkout sites
$ python bin/guicavane # con esto abris guicavane cada vez

**Comment by ivanalejandro0** [comment]
excelente, gracias por su trabajo!
