### ISSUE TITLE
Error al abrir Guicavane

### ISSUE THREAD

**Issue by frangarciaw92** [j0hn/guicavane#24]
Cuando abro Guicavane desde windows, este me lanza este error:

The logfile 'C:\Program Files\Guicavane\guicavane.ese.log' could not be opened: [Errno 13] Permission denied: 'C:\Program Files\Guicavane\guicavane.exe.log

En consecuencia de este error las listas de series y películas no se cargan. ¿Hay una posible solución para el problema?
Gracias

**Comment by javis** [comment]
A mi no me tira ningun error pero tampoco me carga nada. Probe ejecutarlo como admin en win 7 y tampoco funcionó

**Comment by j0hn** [comment]
En estos momentos no va a andar guicavane en windows. Estamos arreglando para que ande con el nuevo sitio antes de poder generar otro instalador. En cuanto pueda voy a hacer un instalador nuevo para windows.

@frangarciaw92 De todas formas, el problema que te está dando parece ser por permisos. No tengo idea como funciona en windows ese tema, algo mejor alguien que tenga más idea te puede ayudar... De ultima podes probar instalando el programa en Mis Documentos o algo por el estilo que no deberías tener problemas de permisos.

**Comment by javis** [comment]
Por el tema de permisos en Windows 7, podes probar con boton derecho del mouse sobre el icono del programa-> ejcutar como administrador.

**Comment by j0hn** [comment]
FYI, acabo de generar un instalador con la versión en desarrollo. Pueden probarla bajandolo de aca: https://github.com/downloads/j0hn/guicavane/guicavane-1.6.1-BETA-install.exe y reportarme bugs si encuentran.

Saludos

**Comment by javis** [comment]
ahora mismo lo estoy bajando, gracias!

**Comment by javis** [comment]
-    El listado de shows aparece bien
-    Latest movies & Recomended movies tira un error de try again later con cualquier sitio
-    La busqueda anda bien en cualquier sitio

Muchas gracias por el update! voy a seguir posteando a medida que encuentre cosas

**Comment by j0hn** [comment]
Si, todavía no está hecha la parte de Latest movies ni Recomended movies en ninguno de los sitios.

Dale, reportame cualquier cosa que veas.

PD: Si queres probar freevana ("aka cuevana offline") tenes que bajar la base de datos de: http://tirino.github.com/freevana/ y ponerla en tu carpeta de configuración que no sé como es en windows =P pero es en donde está el archivo "guicavane.conf" (a lo mejor una busqueda te dice en donde está)

**Comment by javis** [comment]
Dale, mas tarde la bajo y te cuento como me fue.

2011/12/2 Gonzalo Garcia Berrotaran <
reply@reply.github.com

**Comment by javis** [comment]
Hola!

queria reportar que las descargan no me funcionan. 

parece avanzar hasta completar el 100% de las descargas pero me crea un archivo de 0 bytes sin extension.

**Comment by j0hn** [comment]
podrías dar más detalles? eso es en linux o windows? con una serie o una pelicula? cual serie o cual pelicula? todas? con que sitio? que sitio de descargas? (megaupload, bitshare, etc)

**Comment by javis** [comment]
seguro!:
-    OS: Windows
-    Pelicula: Batman under the red hood (recien empezo a dar otro error, index out of bound o algo parecido, pero hasta hace 1 hora funcionaba) No probé otra peli
-    Sitio: Cuevana
-    Sitio descarga: Megaupload

**Comment by j0hn** [comment]
Bueno, todavía no probé en windows pero en linux está andando perfectamente. Por las dudas decime cual fue el instalador que usaste.

Gracias :D

**Comment by javis** [comment]
use el 1.6.1 BETA, gracias :)

**Comment by j0hn** [comment]
Tampoco me pasa en windows, podes confirmar que te sigue sucediendo esto?

A mi me anda perfectamente: http://i.imgur.com/VD23A.jpg

**Comment by javis** [comment]
ojo que yo no le puse bajar y reproducir, le di al boton de solamente bajar,

**Comment by javis** [comment]
acabo de probar de nuevo con la misma peli y me dice, error al obtener el link de megaupload: index out of range

**Comment by j0hn** [comment]
Puede ser que ya se haya bajado por completo y que guicavane esté tratando de volver a bajar desde donde quedó pero si está completo megaupload se va a quejar. Podes fijarte si la pelicula está completamente bajada en tu carpeta de cache (o en donde la hayas bajado). Si no es eso intentá borrar el archivo que haya creado y bajarla de nuevo.

Muchas gracias

**Comment by javis** [comment]
el unico archivo que veo es de 0 bytes. no se donde mas puede estar la
carpeta cache. alguna pista?

2011/12/8 Gonzalo Garcia Berrotaran <
reply@reply.github.com

**Comment by j0hn** [comment]
anda a tu archivo de configuración de guicavane (C:\Documents and Settings<TU_USUARIO>.guicavane\guicavane.conf) y fijate en donde dice "cache_dir", ahí te está guardando el archivo.

Podes probar desde la interfaz misma, cambiarle la configuración del cache hacia tu escritorio por ejemplo, y probar ahí

**Comment by javis** [comment]
Gracias,

Me baje la version nueva y probe bajarme la misma peli desde otra fuente y
me hizo exactamente lo mismo, me termino la descarga en algun momento, (yo
no estaba viendo la pantalla cuando termino, asi que no se que paso) pero
cuando volvi la barra de progreso habia desaparecido.

Fui al directorio donde habia elegido guardar la pelicula, y solamente
habia un archivo llamado 'batman' de 0 bytes.

me fui al directorio cache segun tus indicaciones, esta en c:\downloads.
 estaba vacio.

saludos!

2011/12/8 Gonzalo Garcia Berrotaran <
reply@reply.github.com

**Comment by j0hn** [comment]
esto me está inquietando =P

Podes pasarme un archivo que se llama Guicavane.exe.log que está en la carpeta de instalación de guicavane?

**Comment by javis** [comment]
Ahi va! no se si te va a llegar por aca, pero trato.

Tampoco se que hacemos despiertos a esta hora XD

2011/12/9 Gonzalo Garcia Berrotaran <
reply@reply.github.com

**Comment by j0hn** [comment]
no lleg nada, mandamelo directo a mi mail. Gracias.

On Fri, Dec 9, 2011 at 3:36 AM, Javier Arias <
reply@reply.github.com

**Comment by j0hn** [comment]
Ya encontré el problema! El tema era con las automatic marks, estaba trabajando como si fuera una serie y en realidad era una pelicula... debo haber tenido desactivada esa opción cuando probé yo.

De todas formas, no explica que guarde 0 bytes, eso solo falla al final cuando trata de guardar la pelicula en la lista de marcas...

**Comment by javis** [comment]
hum. sera un tema de permisos para escribir en el archivo? nah, no podria ni crear el archivo...

**Comment by javis** [comment]
a todo esto, hay esperanzas? XD proba bajando una peli nomas, no la pongas a reproducir, quizas te pasa lo mismo asi.

**Comment by javis** [comment]
hey, no tenes una version nueva para probar? alguna sin marcadores por lo menos? hace bocha que no puedo bajarme ninguna :S

**Comment by frangarciaw92** [comment]
Yo tenía los mismos problemas y se solucionaron al bajarme este instalador:
guicavane-develop.exe
7.0MB · Uploaded about 21 hours ago

**Comment by javis** [comment]
lo prob, inclusive probe desde ubuntu y sigo teniendo los mismos dramas.

La peli es Aliens 2 "el regreso" asi prueban y me dicen si les pasa lo
mismo.

On Mon, Dec 12, 2011 at 9:02 PM, frangarciaw92 <
reply@reply.github.com

**Comment by j0hn** [comment]
cuando tenga un tiempito sigo viendo esto, disculpen

**Comment by j0hn** [comment]
acabo de generar otro instalador para la versión de desarollo, podrías probar con esta versión a ver si seguis teniendo los mismos problemas? https://github.com/downloads/j0hn/guicavane/guicavane-develop.exe

Yo estoy bajando sin problemas un capitulo de una serie en windows (bajando sin reproducir)

**Comment by javis** [comment]
Buenisimo!

este funcionó! muchisimas gracias! LOS QUIERO! XD
