### ISSUE TITLE
Minor request: link in 'About' should open default browser

### ISSUE THREAD

**Issue by ghost** [j0hn/guicavane#25]
(Sorry I pressed the wrong key)

Right now the link in the 'About' section opens Firefox, it should be the default browser.

**Comment by j0hn** [comment]
A mi no me pasa esto, uso google chrome y el about me abre en google chrome

**Comment by ghost** [comment]
Será algo de Ubuntu entonces, a mí me abre Firefox y mi navegador predeterminado es Chrome. Es una pavada igual...
