### ISSUE TITLE
Error obtaining link in windows

### ISSUE THREAD

**Issue by pabratte** [j0hn/guicavane#29]
I send a screenshot of an error using the latest git version in windows (build with the .bat script). It hapens with most of the movies, but not with all of them (ej: Pirates of Silicon Valley downloads ok). Also the option "Automatically use megaupload" doesn't seem to work.

http://imageshack.us/photo/my-images/694/scshots.jpg/

**Comment by j0hn** [comment]
That happends when the file does not exists on megaupload anymore, we should throw a better error message... 

Also, if you're using git in windows you should use the develop branch, it has some fixes and better stuff always, like that automatically use megaupload fixed... just a recomendation.

**Comment by pabratte** [comment]
Yes, but the movie can be seen from cuevana (or downloaded from the linux version), so i don't think it's a problem of non existing files. Tried with the develop branch but still getting the same error.

This is the content of the .log file:

[2011-12-11 22:59:07,622] Hosts WARNING: Couldn't import guicavane.Hosts.Freevana api: Database file does not exists

C:\Program Files\Guicavane\library.zip\guicavane\GuiManager.py:568: GtkWarning: Could not find the icon '"C:\Program Files\VideoLAN\VLC\vlc.exe",0'. The 'hicolor' theme

was not found either, perhaps you need to install it.

You can get a copy from:

```
http://icon-theme.freedesktop.org/releases
```

[2011-12-11 22:59:25,355] ThreadRunner ERROR: running: Megaupload.get_megalink, args: (), kwargs: {}

Details:

Traceback (most recent call last):

  File "guicavane\ThreadRunner.pyc", line 50, in run

  File "guicavane\Downloaders\Megaupload.pyc", line 80, in get_megalink

IndexError: list index out of range

**Comment by j0hn** [comment]
mmm, maybe it's the new megaupload's waiting time, try with this version: https://github.com/downloads/j0hn/guicavane/guicavane-develop.exe

**Comment by pabratte** [comment]
no luck... still having the same error...
http://imageshack.us/photo/my-images/35/scshot2.jpg/

**Comment by j0hn** [comment]
try cleaning out the cache, it may have an old version of the megaupload page...

On Sun, Dec 11, 2011 at 11:57 PM, Pablo Abratte
reply@reply.github.com
wrote:

**Comment by pabratte** [comment]
No sure about what cache are you talking about... I changed the programs's cache folder to an empty one but didn't worked...
