### ISSUE TITLE
Error fetching hosts: list index out of range

### ISSUE THREAD

**Issue by sidaphextwin** [j0hn/guicavane#32]
Siempre me ha funcionado guicavane en parabola linux. Ahora cuando intento ver una serie o película seleccionando en la lista monsterdivx sale el siguiente error: Error fetching hosts: list index out of range.
Si intento ver la serie/pelicula de cuevana salta este: Error obtaining megaupload's link: list index out of range.

:-)

**Comment by j0hn** [comment]
Gracias por el reporte. Acabo de arreglar el problema de Monsterdivx y lo de Cuevana es porque megaupload borró muchisimos archivos (y encima los reemplazó por una canción de publicidad). Igual ahora guicavane da un error más detallado diciendo que el archivo fue borrado.

Esto está arreglado en la versión de desarrollo, si queres usarla ya mismo tenes que moverte al branch develop o esperar hasta que meta los cambios en el master.

Gracias!

**Comment by sidaphextwin** [comment]
Gracias a ti por los cambios y la rapidez con que los reparaste.

La verdad es que a los que nos gusta ver películas on-line y usamos distribuciones gnu/linux 100% libres nos es muy preciado tu programa por que no hay modo de verlas por navegador.

¿Puedes decirme que nombre tiene el paquete para guicavane de desarrollo? El que tengo instalado es guicavane-git...

Un abrazo!
