### ISSUE TITLE
Include "next movies" and "next episodes" in search

### ISSUE THREAD

**Issue by leogallego** [j0hn/guicavane#7]
Right next to "Latest movies" and "Latest show episodes", there is a next movies and episodes, where you can find more. This are not listed in the normal search. It would be nice to have access to this from Guicavane.

**Comment by j0hn** [comment]
Yes, its a nice feature, but there are many "latest movies" to get them all... maybe we could get only the first (or maybe first 3 depending on the lag) page or something like that because it will take forever to search a movie if i have to check all the 10 pages (at this moment) of new movies.

**Comment by j0hn** [comment]
It's now implemented on the Develop branch, please test it and let me now if there is any issues :)

Thanks!

PD: as i said, it search on the first 3 pages for matching movies, it's configurable through code if you want to try a higher number and see how slow makes the search.

**Comment by leogallego** [comment]
Thanks for the fast response. Will try it and comment soon.

**Comment by leogallego** [comment]
Tested, seems to work fine and fast. Thanks!

Can't think of a better way to access the whole pages without making it dead slow, so, for now, I think this is just fine!

Thanks again.

**Comment by leogallego** [comment]
I don't know if something changed, but I can't see the "next movies" listed anymore.

The dropdown for "latest movies" works great, but that's another list. And searching for a movie name, doesn't include the results from the "next" pages.

**Comment by j0hn** [comment]
It looks like it isn't working, will take a look when i find some time free...
