### ISSUE TITLE
Allow to continue using the interface while playing

### ISSUE THREAD

**Issue by leogallego** [j0hn/guicavane#8]
It would be nice to be able to continue using the interface while playing, so that you can search another show or movie.

PS: Hope you don't mind me "wishlisting" in the issues, but think of it as a compliment to your app!

**Comment by j0hn** [comment]
I could do that, but does it makes sense? The only reason i find to do that is to download multiple files at once if you have a megaupload premium account. Can you explain more why you would like to have this?

PS: I don't mind at all, please keep the feedback comming :)

**Comment by leogallego** [comment]
This would allow to download another show in the background once the "choice of provider" is available.

Might not be a necessity but at least I would find it useful ;)
